use anchor_lang::prelude::*;

mod constants;
mod errors;
mod events;
mod instructions;
mod state;

use instructions::*;

declare_id!("SLLeM4ZCQKdUjFQd8e5Pfx2RoG1E6Q3K7GnQxABo8yH");

#[program]
pub mod solana_log_lab {
    use super::*;

    /// Emits plain runtime logs using `msg!`.
    /// Demonstrates basic Solana text logs (debug-oriented, non-structured).
    pub fn log_plain(ctx: Context<LogPlain>) -> Result<()> {
        log_plain::log_plain(ctx)
    }

    /// Emits a structured Anchor event using `emit!`.
    /// Demonstrates how events are serialized into `Program data` logs.
    pub fn log_event(ctx: Context<LogEvent>) -> Result<()> {
        log_event::log_event(ctx)
    }

    /// Intentionally fails using `require!` to emit an error log.
    /// Demonstrates Anchor error propagation and error log visibility.
    pub fn log_error(ctx: Context<LogError>) -> Result<()> {
        log_error::log_error(ctx)
    }

    /// Performs a CPI call to the System Program.
    /// Demonstrates implicit runtime logs (`invoke` / `success`) generated by CPI.
    pub fn log_cpi(ctx: Context<LogCpi>, lamports: u64) -> Result<()> {
        log_cpi::log_cpi(ctx, lamports)
    }

    /// Writes a persistent on-chain log entry into an account.
    /// Demonstrates state-based logging for audit/history use cases.
    pub fn log_state(ctx: Context<LogState>, kind: u8, message: String) -> Result<()> {
        log_state::log_state(ctx, kind, message)
    }
}
